name: 'Test oasdiff actions'
on:
  pull_request:
  push:
jobs:
  oasdiff_diff:
    runs-on: ubuntu-latest
    name: Test diff action
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'swagger-sample/swagger-develop.yaml'
          revision: 'swagger-sample/swagger-test.yaml'
          format: 'text'
          output-to-file: 'diff.txt'
      - name: Test diff action output to file
        run: |
          if [ ! -s diff.txt ]; then
            echo "Diff file doesn't exist or is empty"
            exit 1
          fi

  oasdiff_breaking:
    runs-on: ubuntu-latest
    name: Test breaking action
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Running OpenAPI Spec breaking action
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          base: 'swagger-sample/swagger-develop.yaml'
          revision: 'swagger-sample/swagger-test.yaml'

  oasdiff_changelog:
    runs-on: ubuntu-latest
    name: Test breaking action
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Running OpenAPI Spec changelog action
        uses: oasdiff/oasdiff-action/changelog@main
        with:
          base: 'swagger-sample/swagger-develop.yaml'
          revision: 'swagger-sample/swagger-test.yaml'
          output-to-file: "changelog.txt"
      - name: Test changelog action output
        run: |
          output=$(echo "${{steps.test_changelog.outputs.changelog}}" | head -n 1)
          if [[  "${output}" != "${OASDIFF_ACTION_TEST_EXPECTED_OUTPUT}" ]]; then
            echo "Expected output '$OASDIFF_ACTION_TEST_EXPECTED_OUTPUT' but got '${output}'" >&2
            exit 1
          fi
      - name: Test changelog action output to file
        run: |
          if [ ! -s changelog.txt ]; then
            echo "Changelog file doesn't exist or is empty"
            exit 1
          fi
          output=$(cat changelog.txt | head -n 1)
          if [[  "${output}" != "${OASDIFF_ACTION_TEST_EXPECTED_OUTPUT}" ]]; then
            echo "Expected output '$OASDIFF_ACTION_TEST_EXPECTED_OUTPUT' but got '${output}'" >&2
            exit 1
          fi
